# SSH HARDENING
# ===================================================================

configure_ssh() {
    log_header "CONFIGURING SSH SECURITY"
    
    backup_file "/etc/ssh/sshd_config"
    
    log_info "Configuring SSH on port $SSH_PORT (keeping port 22 temporarily)"
    
    cat > /etc/ssh/sshd_config <<EOF
# ===================================================================
# SSH Server Configuration - Security Hardened
# Generated by VPS Setup Script on $(date)
# ===================================================================

# Network
Port 22
Port $SSH_PORT
AddressFamily inet
ListenAddress 0.0.0.0

# Protocol
Protocol 2

# Host Keys
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Ciphers and Algorithms (Modern, Secure)
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512

# Authentication
LoginGraceTime 60
PermitRootLogin yes
StrictModes yes
MaxAuthTries 3
MaxSessions 5
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PasswordAuthentication yes
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Security Features
IgnoreRhosts yes
HostbasedAuthentication no
PermitUserEnvironment no
AllowAgentForwarding no
AllowTcpForwarding no
X11Forwarding no
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
PermitTunnel no
Banner none

# Connection Management
ClientAliveInterval 300
ClientAliveCountMax 2
MaxStartups 10:30:60

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Subsystems
Subsystem sftp /usr/lib/openssh/sftp-server -f AUTHPRIV -l INFO

# Override for specific users (if needed)
Match User $NEW_USER
    PasswordAuthentication yes
EOF

    # Test SSH configuration
    if sshd -t; then
        systemctl reload ssh
        log_success "SSH configured successfully"
        log_warning "SSH is listening on BOTH port 22 and $SSH_PORT for safety"
    else
        log_error "SSH configuration test failed!"
        log_info "Restoring backup..."
        cp "${BACKUP_DIR}/sshd_config.backup" /etc/ssh/sshd_config
        systemctl reload ssh
        exit 1
    fi
}

create_ssh_hardening_script() {
    log_info "Creating SSH hardening script..."
    
    cat > "/home/$NEW_USER/harden-ssh.sh" <<'EOFSCRIPT'
#!/bin/bash
# SSH Hardening Script - Run after testing SSH connection

set -e

echo "╔════════════════════════════════════════════════════════╗"
echo "║         SSH HARDENING - FINAL LOCKDOWN                 ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "This will:"
echo "  • Disable root login"
echo "  • Disable password authentication"
echo "  • Remove port 22 (keep only custom port)"
echo ""
echo "⚠️  WARNING: This may lock you out if:"
echo "  • SSH keys are not properly configured"
echo "  • Custom port is blocked by firewall"
echo "  • You haven't tested the new configuration"
echo ""

read -rp "Have you tested SSH on the new port? (yes/no): " confirm

if [[ "$confirm" != "yes" ]]; then
    echo "❌ Cancelled. Test the connection first!"
    exit 1
fi

echo "🔒 Hardening SSH configuration..."

sudo tee /etc/ssh/sshd_config > /dev/null <<'EOFSSH'
Port 2222
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Hardened Authentication
LoginGraceTime 30
PermitRootLogin no
StrictModes yes
MaxAuthTries 2
MaxSessions 2
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Security
IgnoreRhosts yes
HostbasedAuthentication no
AllowAgentForwarding no
AllowTcpForwarding no
X11Forwarding no

# Connection
ClientAliveInterval 300
ClientAliveCountMax 2

Subsystem sftp /usr/lib/openssh/sftp-server
EOFSSH

if sudo sshd -t; then
    sudo systemctl restart ssh
    echo "✅ SSH hardened successfully!"
    echo "📝 Remember: ssh $USER@server -p 2222"
else
    echo "❌ Configuration error! SSH not restarted."
    exit 1
fi
EOFSCRIPT

    chmod +x "/home/$NEW_USER/harden-ssh.sh"
    chown "$NEW_USER:$NEW_USER" "/home/$NEW_USER/harden-ssh.sh"
    
    log_success "Hardening script created: /home/$NEW_USER/harden-ssh.sh"
}

# ===================================================================
# FIREWALL CONFIGURATION
# ===================================================================

setup_firewall() {
    log_header "CONFIGURING UFW FIREWALL"
    
    log_info "Resetting firewall rules..."
    ufw --force reset
    
    log_info "Setting default policies..."
    ufw default deny incoming
    ufw default allow outgoing
    
    log_info "Allowing SSH ports..."
    ufw allow 22/tcp comment 'SSH - Temporary'
    ufw allow "$SSH_PORT/tcp" comment 'SSH - Custom Port'
    
    log_info "Allowing HTTP/HTTPS..."
    ufw allow 80/tcp comment 'HTTP'
    ufw allow 443/tcp comment 'HTTPS'
    
    log_info "Enabling firewall..."
    ufw --force enable
    
    log_success "Firewall configured and enabled"
    ufw status numbered
}

# ===================================================================
# FAIL2BAN CONFIGURATION
# ===================================================================

setup_fail2ban() {
    log_header "CONFIGURING FAIL2BAN"
    
    backup_file "/etc/fail2ban/jail.local"
    
    cat > /etc/fail2ban/jail.local <<EOF
# ===================================================================
# Fail2Ban Configuration
# Generated by VPS Setup Script on $(date)
# ===================================================================

[DEFAULT]
# Ban settings
bantime = 3600
findtime = 600
maxretry = 3
backend = systemd
destemail = $EMAIL
sendername = Fail2Ban
action = %(action_mwl)s

# Ignore local connections
ignoreip = 127.0.0.1/8 ::1

[sshd]
enabled = true
port = ssh,$SSH_PORT
filter = sshd
logpath = %(sshd_log)s
maxretry = 3
bantime = 7200

[nginx-http-auth]
enabled = true
port = http,https
filter = nginx-http-auth
logpath = /var/log/nginx/error.log
maxretry = 3

[nginx-noscript]
enabled = true
port = http,https
filter = nginx-noscript
logpath = /var/log/nginx/access.log
maxretry = 6

[nginx-badbots]
enabled = true
port = http,https
filter = nginx-badbots
logpath = /var/log/nginx/access.log
maxretry = 2

[nginx-noproxy]
enabled = true
port = http,https
filter = nginx-noproxy
logpath = /var/log/nginx/access.log
maxretry = 2

[nginx-limit-req]
enabled = true
port = http,https
filter = nginx-limit-req
logpath = /var/log/nginx/error.log
maxretry = 10
findtime = 300
bantime = 7200
EOF

    systemctl enable fail2ban
    systemctl restart fail2ban
    
    log_success "Fail2Ban configured and started"
}

